version: "3"

services:
  #############################
  # ELASTICSEARCH MASTER NODE #
  #############################
  sarccom-master:
    restart: unless-stopped
    image: blacktop/elasticsearch:6.2
    environment:
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - cluster.name=docker-cluster
      - node.master=true
      - node.ingest=false
      - node.data=false
    # volumes:
    #  - data:/usr/share/elasticsearch/data
    networks:
      - elastic
  ####################################
  # ELASTICSEARCH CLIENT/INGEST NODE #
  ####################################
  sarccom-ingest:
    restart: unless-stopped
    image: blacktop/elasticsearch:6.2
    environment:
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - cluster.name=docker-cluster
      - node.master=true
      - node.ingest=true
      - node.data=false
      - discovery.zen.ping.unicast.hosts=sarccom-master
    ports:
      - "9200:9200"
    links:
     - sarccom-master:elastic-master
    networks:
      - elastic
  ###########################
  # ELASTICSEARCH DATA NODE #
  ###########################
  sarccom-data:
    restart: unless-stopped
    image: blacktop/elasticsearch:6.2
    environment:
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - cluster.name=docker-cluster
      - node.master=false
      - node.ingest=false
      - node.data=true
      - discovery.zen.ping.unicast.hosts=sarccom-master
    links:
     - sarccom-master:elastic-master
    volumes:
      - data:/usr/share/elasticsearch/data
    networks:
      - elastic
  ###############
  # KIBANA NODE #
  ###############
  sarccom-kibana:
    image: blacktop/kibana:6.2
    ports:
      - "5601:5601"
    links:
     - sarccom-ingest:elasticsearch
    networks:
      - elastic
    depends_on: ['sarccom-master']
  ###############
  # LOGSTASH NODE #
  ###############
  sarccom-logstash:
    restart: unless-stopped
    image: "blacktop/logstash:6.2"
    ports:
      - "5000:5000"
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/config/logstash.conf
      - ./logstash/mysql-connector-java-8.0.13.jar:/usr/share/logstash/config/mysql-connector-java-8.0.13.jar
      - ./logstash/last_run.txt:/usr/share/logstash/config/last_run.txt
    command: logstash -f /usr/share/logstash/config/logstash.conf
    networks:
      - elastic
    depends_on: ['sarccom-ingest','sarccom-db']
  ###############
  # MYSQL NODE #
  ###############
  sarccom-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'sarccom_db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'sarccom'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'sarccom-keren-banget'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'sarccom-is-the-best'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - "my-db:/var/lib/mysql"
    networks:
      - elastic
#############################
# DATA VOLUME #
#############################
volumes:
  data:
  my-db:
################################
# ELASTICSEARCH BRIDGE NETWORK #
################################
networks:
  elastic:
    driver: bridge
